spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: Andrey1965
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    #        dialect: org.hibernate.dialect.MySQL5Dialect
#  ?useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=UTC
sites:
#    - url: https://dimonvideo.ru
#      name: DimonVideo
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: http://www.playback.ru
      name: PlayBack.ru

connect:
  useragent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com

webinterface: /admin